# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cardinal Wizards' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Mapbox-iOS-SDK', '~> 3.6'

  # Pods for Cardinal Wizards

  target 'Cardinal WizardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Cardinal WizardsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
